services:
    GGGGino\SkuskuCartBundle\EventSubscriber\CurrencySubscriber:
        arguments: ['%currency%']
        # redundant if you're using autoconfigure
        tags: [kernel.event_subscriber]

    GGGGino\SkuskuCartBundle\Service\CurrencyManager:
        public: true
        arguments: ['@doctrine.orm.default_entity_manager', '@security.token_storage', '@request_stack']

    GGGGino\SkuskuCartBundle\Service\LangManager:
        public: true
        arguments: ['@doctrine.orm.default_entity_manager', '@security.token_storage', '@request_stack']

    GGGGino\SkuskuCartBundle\Service\CartManager:
        public: true
        arguments: ['@doctrine.orm.default_entity_manager', '@security.token_storage', '%ggggino_skuskucart.allow_anonymous_shop%']
        calls:
            - [setCurrencyManager, ['@GGGGino\SkuskuCartBundle\Service\CurrencyManager']]
            - [setLangManager, ['@GGGGino\SkuskuCartBundle\Service\LangManager']]

    GGGGino\SkuskuCartBundle\Service\OrderManager:
        public: true
        arguments: ['@doctrine.orm.default_entity_manager', '@security.token_storage', '%ggggino_skuskucart.allow_anonymous_shop%']

    GGGGino\SkuskuCartBundle\Form\CartFlow:
        parent: craue.form.flow
        class: GGGGino\SkuskuCartBundle\Form\CartFlow
        arguments: ['%ggggino_skuskucart.stepform%', '@GGGGino\SkuskuCartBundle\Service\CartManager', '@GGGGino\SkuskuCartBundle\Service\OrderManager', '@request_stack']
        public: true
        calls:
            - [setPayum, ['@payum']]

    GGGGino\SkuskuCartBundle\Service\SkuskuHelper:
        public: true
        arguments: ['@doctrine.orm.default_entity_manager', '%skusku_abstract_entities%']

    GGGGino\SkuskuCartBundle\Twig\CartExtension:
        class: GGGGino\SkuskuCartBundle\Twig\CartExtension
        public: false
        arguments: ['@twig', '@GGGGino\SkuskuCartBundle\Service\CartManager', '@GGGGino\SkuskuCartBundle\Service\CurrencyManager', '@GGGGino\SkuskuCartBundle\Service\LangManager']
        tags:
            - { name: twig.extension }

    Payum\Core\Bridge\Symfony\Form\Type\GatewayChoiceType:
        arguments: ["%skusku_gateways%"]
        tags:
            - { name: form.type }