language: php

sudo: false

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

matrix:
  allow_failures:
    - php: 5.6
  fast_finishe: true

before_install:
  - composer self-update
  - mysql -e 'CREATE DATABASE myapp_test;'

install:
  - composer install --optimize-autoloader --prefer-source

script:
  - vendor/bin/phpunit --verbose